### ISSUE TITLE
MTK无法运行在 GPU 上

### ISSUE THREAD

**Issue by Kasq-Lee** [DayBreak-u/chineseocr_lite#174]
在 MTK 平台上测试，Android 系统，ncnn project，demo 的 models 无法运行在 GPU 上，能跑起来得到结果，但未在 GPU 上运行，GPU 未被占用。速度并未加快

**Comment by cqray1990** [comment]
> 在 MTK 平台上测试，Android 系统，ncnn project，demo 的 models 无法运行在 GPU 上，能跑起来得到结果，但未在 GPU 上运行，GPU 未被占用。速度并未加快

 我也遇到这个问题，在gpu上跑ncnn project out of blob allocator
out of staging allocator  在cpu上跑就正常
