### ISSUE TITLE
[W:onnxruntime:, graph.cc:2709 CleanUnusedInitializers]  unused_initializer优化问题

### ISSUE THREAD

**Issue by terancejiang** [DayBreak-u/chineseocr_lite#256]
运行时报onnxruntime warning
![image](https://user-images.githubusercontent.com/14614923/94354638-c471c800-00af-11eb-81bc-ad60fb1661aa.png)
尝试使用 onnx.optimizer优化报错
![image](https://user-images.githubusercontent.com/14614923/94354653-f71bc080-00af-11eb-94fc-0a647522c3f0.png)

有哪位大佬知道怎么搞吗，把warning关掉也行

**Comment by lindatas** [comment]
需要修改模型数据。手动清理导出的模型，可以解决这个问题，参考下面的代码

```
import onnx
import onnxoptimizer as optimizer
onnxfile = "chineseocr_lite-onnx\\models\\crnn_lite_lstm.onnx"
onnx_model = onnx.load(onnxfile)
passes = ["extract_constant_to_initializer", "eliminate_unused_initializer"]
optimized_model = optimizer.optimize(onnx_model, passes)
onnx.save(optimized_model, onnxfile)
```
