### ISSUE TITLE
报错 Segmentation fault

### ISSUE THREAD

**Issue by aleimu** [DayBreak-u/chineseocr_lite#29]
device: cpu
load model
device: cpu
load model
device: cpu
load model
device: cpu
load model
http://0.0.0.0:8080/
36.27.60.250:56848 - - [12/Mar/2020 11:14:48] "HTTP/1.1 GET /ocr" - 200 OK
Segmentation fault

上传一个图片识别后,直接就报了Segmentation fault这个错误,我是在阿里云上跑的,难道是硬件不支持?

**Comment by lllfx** [comment]
pytorch的问题

**Comment by aleimu** [comment]
> pytorch的问题

我是在https://pytorch.org 选择了pip install torch==1.4.0+cu92 torchvision==0.5.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html 执行的,好像选不到torch==1.2.0的版本

**Comment by yujinyj** [comment]
> > pytorch的问题
> 
> 我是在https://pytorch.org 选择了pip install torch==1.4.0+cu92 torchvision==0.5.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html 执行的,好像选不到torch==1.2.0的版本

我重装了torch 1.20 也是一样的问题，不知道如果定位更详细的错误
https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp36-cp36m-manylinux1_x86_64.whl

https://download.pytorch.org/whl/cpu/torchvision-0.4.0%2Bcpu-cp36-cp36m-manylinux1_x86_64.whl

**Comment by Only-yaya** [comment]
也是遇到了同样的问题.这种问题自己真的不好解决,作者能否给出解决办法.感谢

**Comment by DarrenLee618** [comment]
我也是这个错误，直接Segmentation fault后退出

**Comment by DarrenLee618** [comment]
也是相同问题，应该不是torch版本的问题，公众号机器之心是用torch 1.5跑通的。错误定位到是调用c++模块那边，作者能否给出解决方法，谢谢

**Comment by lllfx** [comment]
> > > pytorch的问题
> > 
> > 
> > 我是在https://pytorch.org 选择了pip install torch==1.4.0+cu92 torchvision==0.5.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html 执行的,好像选不到torch==1.2.0的版本
> 
> 我重装了torch 1.20 也是一样的问题，不知道如果定位更详细的错误
> https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp36-cp36m-manylinux1_x86_64.whl
> 
> https://download.pytorch.org/whl/cpu/torchvision-0.4.0%2Bcpu-cp36-cp36m-manylinux1_x86_64.whl


我是用的anaconda，创建了一个py352版本的环境，torch时通过conda命令安装的

**Comment by yujinyj** [comment]
@aleimu @lllfx @Only-yaya @DarrenLee618 
已经解决，升级到 gcc4.9，重新编译pse.so然后就可以了

**Comment by light1003** [comment]
> @aleimu @lllfx @Only-yaya @DarrenLee618
> 已经解决，升级到 gcc4.9，重新编译pse.so然后就可以

还是崩。。。

**Comment by SilenceBlue** [comment]
一样的问题，求解决方案
