### ISSUE TITLE
What kind of environment do you use

### ISSUE THREAD

**Issue by duolabmeng6** [DayBreak-u/chineseocr_lite#75]
➜ python app.py 8080
find: -xtype: unknown primary or operator
make: `pse.so' is up to date.
device: cpu
load model
device: cpu
load model
device: cpu
load model
device: cpu
load model
Traceback (most recent call last):
  File "/Users/xxx/opt/anaconda3/lib/python3.7/site-packages/web/utils.py", line 526, in take
    yield next(seq)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 125, in <module>
    app = web.application(urls, globals())
  File "/Users/xxx/opt/anaconda3/lib/python3.7/site-packages/web/application.py", line 62, in __init__
    self.init_mapping(mapping)
  File "/Users/xxx/opt/anaconda3/lib/python3.7/site-packages/web/application.py", line 130, in init_mapping
    self.mapping = list(utils.group(mapping, 2))
  File "/Users/xxx/opt/anaconda3/lib/python3.7/site-packages/web/utils.py", line 531, in group
    x = list(take(seq, size))
RuntimeError: generator raised StopIteration
(base)

**Comment by wscnwps** [comment]
> ➜ python app.py 8080
> find: -xtype: unknown primary or operator
> make: `pse.so' is up to date.
> device: cpu
> load model
> device: cpu
> load model
> device: cpu
> load model
> device: cpu
> load model
> Traceback (most recent call last):
> File "/Users/xxx/opt/anaconda3/lib/python3.7/site-packages/web/utils.py", line 526, in take
> yield next(seq)
> StopIteration
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "app.py", line 125, in
> app = web.application(urls, globals())
> File "/Users/xxx/opt/anaconda3/lib/python3.7/site-packages/web/application.py", line 62, in **init**
> self.init_mapping(mapping)
> File "/Users/xxx/opt/anaconda3/lib/python3.7/site-packages/web/application.py", line 130, in init_mapping
> self.mapping = list(utils.group(mapping, 2))
> File "/Users/xxx/opt/anaconda3/lib/python3.7/site-packages/web/utils.py", line 531, in group
> x = list(take(seq, size))
> RuntimeError: generator raised StopIteration
> (base)

Fix bug in file "/Users/xxx/opt/anaconda3/lib/python3.7/site-packages/web/utils.py", line 524.
Use "try catch" here, for example:
               try:
                    yield next(seq)
               except StopIteration:
                    return
